CREATE INDEX `idx_audit_results_userId` ON `audit_results` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_beliefs_userId` ON `beliefs` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_beta_access_userId` ON `beta_access` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_btw_audio_items_userId` ON `btw_audio_items` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_btw_daily_sessions_userId` ON `btw_daily_sessions` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_btw_gratitude_userId` ON `btw_gratitude_entries` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_btw_ground_checks_userId` ON `btw_ground_checks` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_btw_prayers_userId` ON `btw_prayers` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_btw_returns_userId` ON `btw_returns` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_btw_weekly_reflections_userId` ON `btw_weekly_reflections` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_check_ins_userId` ON `check_ins` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_community_comments_postId` ON `community_comments` (`postId`);--> statement-breakpoint
CREATE INDEX `idx_community_comments_userId` ON `community_comments` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_community_likes_userId` ON `community_likes` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_community_likes_postId` ON `community_likes` (`postId`);--> statement-breakpoint
CREATE INDEX `idx_community_posts_userId` ON `community_posts` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_decisions_userId` ON `decisions` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_energy_audits_userId` ON `energy_audits` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_enrollments_userId` ON `enrollments` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_enrollments_courseId` ON `enrollments` (`courseId`);--> statement-breakpoint
CREATE INDEX `idx_events_userId` ON `events` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_habit_logs_userId` ON `habit_logs` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_habit_logs_habitId` ON `habit_logs` (`habitId`);--> statement-breakpoint
CREATE INDEX `idx_habits_userId` ON `habits` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_journal_entries_userId` ON `journal_entries` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_oracle_conversations_userId` ON `oracle_conversations` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_oracle_insights_userId` ON `oracle_insights` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_orders_userId` ON `orders` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_overflow_captures_userId` ON `overflow_captures` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_pathway_sessions_userId` ON `pathway_sessions` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_referral_codes_ownerId` ON `referral_codes` (`owner_id`);--> statement-breakpoint
CREATE INDEX `idx_referrals_referrerId` ON `referrals` (`referrer_id`);--> statement-breakpoint
CREATE INDEX `idx_scorecards_userId` ON `scorecards` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_user_pathways_userId` ON `user_pathways` (`userId`);